### ISSUE TITLE
zzgg爱死你了😘 催更重积分

### ISSUE THREAD

**Issue by chanbengz** [wLUOw/Introduction_to_Multivariate_Functions#1]
Thanks for sharing it! BTW, when will the multiple integral part come out?

**Comment by LunaQu4kez** [comment]
写这个是因为，发现高数第14章前半的概念以及一些计算，大家都普遍不够熟练并容易混淆。第14章后半及第15章的内容，课本和补充题等资料较为清晰，因此攻略可能没有那么的必要。（btw，先活过期末周，要开始女娲补天了😭）
